Repository oxen-io/session-ios, pull requests merged in 2021-04, with the labels that each got.

#378 Self-Signed Seed Node Certificates
  Session.xcodeproj/project.pbxproj
  Session/Home/HomeVC.swift
  Session/Meta/AppDelegate.m
  Session/Meta/Certificates/public-loki-foundation.crt
  Session/Meta/Certificates/public-loki-foundation.der
  Session/Meta/Certificates/storage-seed-1.crt
  Session/Meta/Certificates/storage-seed-1.der
  Session/Meta/Certificates/storage-seed-3.crt
  Session/Meta/Certificates/storage-seed-3.der
  Session/Meta/Session-Info.plist
  SessionMessagingKit/Open Groups/V2/OpenGroupManagerV2.swift
  SessionSnodeKit/SnodeAPI.swift
  SessionUtilitiesKit/Networking/HTTP.swift
Labels: dev-tested

#381 Make "Select Photos" Option Work
  Session/Conversations/ConversationVC+Interaction.swift
  Session/Meta/Session-Info.plist
  Session/Shared/OWSScreenLockUI.m
  SessionMessagingKit/Utilities/Environment.h
  SessionMessagingKit/Utilities/Environment.m
Labels: dev-tested

#365 Don't Auto-Download Attachments from Untrusted Contacts
  Session.xcodeproj/project.pbxproj
  Session/Conversations/ConversationVC+Interaction.swift
  Session/Conversations/Message Cells/Content Views/MediaPlaceholderView.swift
  Session/Conversations/Message Cells/VisibleMessageCell.swift
  Session/Conversations/Views & Modals/DownloadAttachmentModal.swift
  SessionMessagingKit/Contacts/Contact.swift
  SessionMessagingKit/Database/Storage+Contacts.swift
  SessionMessagingKit/Database/Storage+Jobs.swift
  SessionMessagingKit/Jobs/AttachmentDownloadJob.swift
  SessionMessagingKit/Jobs/JobQueue.swift
  SessionMessagingKit/Sending & Receiving/MessageReceiver+Handling.swift
  SignalUtilitiesKit/Database/Migrations/ContactsMigration.swift
Labels: dev-tested, qa-tested

#390 Fix Open Group Message Timestamp Issue
  Session/Conversations/Message Cells/VisibleMessageCell.swift
  Session/Media Viewing & Editing/MediaGalleryViewController.swift
  SessionMessagingKit/Messages/Signal/TSInteraction.h
  SessionMessagingKit/Messages/Signal/TSInteraction.m
  SignalUtilitiesKit/Messaging/ThreadViewModel.swift
Labels: dev-tested

#391 Fix Conversation Screen Scrolling Bugs (Part 3)
  Session/Conversations/ConversationVC.swift
Labels: dev-tested

#395 Fix Conversation Screen Updating Bug
  Session/Conversations/ConversationViewModel.m
Labels: dev-tested

#394 Improved Snode Pool Updating
  Session.xcodeproj/project.pbxproj
  Session/Closed Groups/EditClosedGroupVC.swift
  Session/Conversations/Settings/OWSConversationSettingsViewController.m
  Session/Home/HomeVC.swift
  Session/Meta/AppDelegate.m
  Session/Open Groups/JoinOpenGroupVC.swift
  Session/Shared/UserCell.swift
  Session/Utilities/BackgroundPoller.swift
  SessionMessagingKit/Database/OWSPrimaryStorage.m
  SessionMessagingKit/Database/Storage+ClosedGroups.swift
  SessionMessagingKit/File Server/FileServerAPIV2.swift
  SessionMessagingKit/Jobs/AttachmentDownloadJob.swift
  SessionMessagingKit/Jobs/AttachmentUploadJob.swift
  SessionMessagingKit/Messages/Control Messages/ClosedGroupControlMessage.swift
  SessionMessagingKit/Messages/Control Messages/ConfigurationMessage.swift
  SessionMessagingKit/Messages/Message.swift
  SessionMessagingKit/Open Groups/V2/OpenGroupAPIV2.swift
  SessionMessagingKit/Open Groups/V2/OpenGroupManagerV2.swift
  SessionMessagingKit/Sending & Receiving/MessageReceiver+Handling.swift
  SessionMessagingKit/Sending & Receiving/MessageSender+ClosedGroups.swift
  SessionMessagingKit/Sending & Receiving/MessageSender.swift
  SessionMessagingKit/Sending & Receiving/Pollers/OpenGroupPollerV2.swift
  SessionMessagingKit/Storage.swift
  SessionMessagingKit/Utilities/ProofOfWork.swift
  SessionSnodeKit/OnionRequestAPI+Encryption.swift
  SessionSnodeKit/OnionRequestAPI.swift
  SessionSnodeKit/Snode.swift
  SessionSnodeKit/SnodeAPI.swift
  SessionSnodeKit/SnodeMessage.swift
  SessionSnodeKit/Storage.swift
  SessionUtilitiesKit/General/Features.swift
  SignalUtilitiesKit/Messaging/OWSAttachmentDownloads.h
  SignalUtilitiesKit/Messaging/OWSAttachmentDownloads.m
  SignalUtilitiesKit/Messaging/Sending & Receiving/MessageSender+Convenience.swift
  SignalUtilitiesKit/Meta/SignalUtilitiesKit.h
  SignalUtilitiesKit/To Do/OWSProfileManager.m
  SignalUtilitiesKit/Utilities/AppSetup.m
Labels: blocked, dev-tested

#396 Remove Unused Strings
  Session/Meta/Translations/de.lproj/Localizable.strings
  Session/Meta/Translations/en.lproj/Localizable.strings
  Session/Meta/Translations/es.lproj/Localizable.strings
  Session/Meta/Translations/fa.lproj/Localizable.strings
  Session/Meta/Translations/fr.lproj/Localizable.strings
  Session/Meta/Translations/id-ID.lproj/Localizable.strings
  Session/Meta/Translations/it.lproj/Localizable.strings
  Session/Meta/Translations/ja.lproj/Localizable.strings
  Session/Meta/Translations/pl.lproj/Localizable.strings
  Session/Meta/Translations/pt_BR.lproj/Localizable.strings
  Session/Meta/Translations/remove_unused_strings.swift
  Session/Meta/Translations/ru.lproj/Localizable.strings
  Session/Meta/Translations/vi-VN.lproj/Localizable.strings
  Session/Meta/Translations/zh_CN.lproj/Localizable.strings
  Session/Onboarding/LandingVC.swift
  Session/Onboarding/LinkDeviceVC.swift
Labels: dev-tested
