Repository oxen-io/session-ios, pull requests merged in 2022-08, with the labels that each got.

#651 Fixed a bug where disappearing messages weren't working for local outgoing messages
  Session/Conversations/ConversationVC+Interaction.swift
  Session/Notifications/AppNotifications.swift
  SessionMessagingKit/Database/Models/OpenGroup.swift
  SessionShareExtension/ThreadPickerVC.swift
Labels: bug

#660 Fixed a bug where deleted incoming messages could incorrectly be counted as unread
  Session.xcodeproj/project.pbxproj
  Session/Meta/AppDelegate.swift
  SessionMessagingKit/Configuration.swift
  SessionMessagingKit/Database/Migrations/_005_FixDeletedMessageReadState.swift
  SessionMessagingKit/Database/Models/DisappearingMessageConfiguration.swift
  SessionMessagingKit/Database/Models/Interaction.swift
  SessionMessagingKit/Database/Models/OpenGroup.swift
  SessionMessagingKit/Sending & Receiving/Message Handling/MessageReceiver+Calls.swift
  SessionMessagingKit/Shared Models/SessionThreadViewModel.swift
Labels: bug, dev-tested

#669 A few bugs fixes and some optimisations
  Session.xcodeproj/project.pbxproj
  Session/Conversations/ConversationVC.swift
  Session/Home/HomeVC.swift
  Session/Home/HomeViewModel.swift
  Session/Home/Message Requests/MessageRequestsViewModel.swift
  Session/Media Viewing & Editing/MediaGalleryViewModel.swift
  Session/Media Viewing & Editing/MediaPageViewController.swift
  Session/Meta/AppDelegate.swift
  Session/Meta/Signal-Bridging-Header.h
  Session/Notifications/AppNotifications.swift
  Session/Notifications/UserNotificationsAdaptee.swift
  Session/Shared/FullConversationCell.swift
  Session/Utilities/BackgroundPoller.swift
  Session/Utilities/IP2Country.swift
  SessionMessagingKit/Configuration.swift
  SessionMessagingKit/Database/Migrations/_003_YDBToGRDBMigration.swift
  SessionMessagingKit/Database/Migrations/_007_HomeQueryOptimisationIndexes.swift
  SessionMessagingKit/Database/Models/Interaction.swift
  SessionMessagingKit/Database/Models/SessionThread.swift
  SessionMessagingKit/Jobs/Types/MessageReceiveJob.swift
  SessionMessagingKit/Meta/SessionMessagingKit.h
  SessionMessagingKit/Open Groups/OpenGroupManager.swift
  SessionMessagingKit/Sending & Receiving/Message Handling/MessageReceiver+VisibleMessages.swift
  SessionMessagingKit/Sending & Receiving/MessageReceiver.swift
  SessionMessagingKit/Sending & Receiving/Notifications/NotificationsProtocol.swift
  SessionMessagingKit/Sending & Receiving/Pollers/ClosedGroupPoller.swift
  SessionMessagingKit/Sending & Receiving/Pollers/OpenGroupPoller.swift
  SessionMessagingKit/Sending & Receiving/Pollers/Poller.swift
  SessionMessagingKit/Shared Models/SessionThreadViewModel.swift
  SessionMessagingKitTests/Open Groups/OpenGroupManagerSpec.swift
  SessionNotificationServiceExtension/NSENotificationPresenter.swift
  SessionNotificationServiceExtension/NotificationServiceExtension.swift
  SessionUtilitiesKit/Database/Types/PagedDatabaseObserver.swift
  SessionUtilitiesKit/JobRunner/JobRunner.swift
  SessionUtilitiesKit/Meta/SessionUtilitiesKit.h
  SessionUtilitiesKit/Utilities/OWSBackgroundTask.h
  SessionUtilitiesKit/Utilities/OWSBackgroundTask.m
  SignalUtilitiesKit/Profile Pictures/ProfilePictureView.swift
  SignalUtilitiesKit/Utilities/NoopNotificationsManager.swift
Labels: qa-tested

#670 Fixed a bug where the "default" notification sound wouldn't be used in the foreground
  Session/Notifications/AppNotifications.swift
Labels: bug

#673 Fixed a few bugs
  Session/Conversations/Context Menu/ContextMenuVC+Action.swift
  Session/Conversations/ConversationVC+Interaction.swift
  SessionMessagingKit/Open Groups/OpenGroupManager.swift
  SessionMessagingKit/Shared Models/MessageViewModel.swift
  SessionUtilitiesKit/Database/Types/PagedDatabaseObserver.swift
  SessionUtilitiesKit/JobRunner/JobRunner.swift
Labels: bug

#674 Fixed a bug where the "DataExtractionNotification" messages weren't correctly setting their tmestamps
  SessionMessagingKit/Sending & Receiving/Message Handling/MessageReceiver+DataExtractionNotification.swift
Labels: bug

#677 Moved the code for a previous fix to the correct location and fixed a build issue
  Session/Conversations/ConversationVC+Interaction.swift
  Session/Notifications/AppNotifications.swift
Labels: bug

#676 Emoji reacts open group poll & update conflict handling
  Session.xcodeproj/project.pbxproj
  Session/Conversations/ConversationVC+Interaction.swift
  SessionMessagingKit/Messages/Message.swift
  SessionMessagingKit/Open Groups/Models/PendingChange.swift
  SessionMessagingKit/Open Groups/Models/ReactionResponse.swift
  SessionMessagingKit/Open Groups/OpenGroupAPI.swift
  SessionMessagingKit/Open Groups/OpenGroupManager.swift
  SessionMessagingKit/Sending & Receiving/MessageReceiver.swift
Labels: qa-tested

#681 Added fixes and defensive coding for a number of crashes
  Session/Onboarding/LandingVC.swift
  SessionMessagingKit/Open Groups/OpenGroupManager.swift
  SessionMessagingKit/Sending & Receiving/Pollers/Poller.swift
  SessionMessagingKit/Utilities/SMKDependencies.swift
  SessionMessagingKitTests/Open Groups/OpenGroupAPISpec.swift
  SessionMessagingKitTests/Open Groups/OpenGroupManagerSpec.swift
  SessionMessagingKitTests/_TestUtilities/DependencyExtensions.swift
  SessionMessagingKitTests/_TestUtilities/MockGeneralCache.swift
  SessionMessagingKitTests/_TestUtilities/MockOGMCache.swift
  SessionMessagingKitTests/_TestUtilities/OGMDependencyExtensions.swift
  SessionSnodeKit/SnodeAPI.swift
  SessionUtilitiesKit/General/Dependencies.swift
Labels: bug
