Repository oxen-io/session-ios, pull requests merged in 2022-09, with the labels that each got.

#646 Add documents section for all media page
  Session.xcodeproj/project.pbxproj
  Session/Media Viewing & Editing/AllMediaViewController.swift
  Session/Media Viewing & Editing/DocumentTitleViewController.swift
  Session/Media Viewing & Editing/MediaGalleryViewModel.swift
  Session/Media Viewing & Editing/MediaPageViewController.swift
  Session/Media Viewing & Editing/MediaTileViewController.swift
  Session/Meta/Translations/de.lproj/Localizable.strings
  Session/Meta/Translations/en.lproj/Localizable.strings
  Session/Meta/Translations/es.lproj/Localizable.strings
  Session/Meta/Translations/fa.lproj/Localizable.strings
  Session/Meta/Translations/fi.lproj/Localizable.strings
  Session/Meta/Translations/fr.lproj/Localizable.strings
  Session/Meta/Translations/hi.lproj/Localizable.strings
  Session/Meta/Translations/hr.lproj/Localizable.strings
  Session/Meta/Translations/id-ID.lproj/Localizable.strings
  Session/Meta/Translations/it.lproj/Localizable.strings
  Session/Meta/Translations/ja.lproj/Localizable.strings
  Session/Meta/Translations/nl.lproj/Localizable.strings
  Session/Meta/Translations/pl.lproj/Localizable.strings
  Session/Meta/Translations/pt_BR.lproj/Localizable.strings
  Session/Meta/Translations/ru.lproj/Localizable.strings
  Session/Meta/Translations/si.lproj/Localizable.strings
  Session/Meta/Translations/sk.lproj/Localizable.strings
  Session/Meta/Translations/sv.lproj/Localizable.strings
  Session/Meta/Translations/th.lproj/Localizable.strings
  Session/Meta/Translations/vi-VN.lproj/Localizable.strings
  Session/Meta/Translations/zh-Hant.lproj/Localizable.strings
  Session/Meta/Translations/zh_CN.lproj/Localizable.strings
  SignalUtilitiesKit/Utilities/CommonStrings.swift
Labels: dev-tested, qa-tested

#647 Media message UI redesign
  Session/Conversations/ConversationVC+Interaction.swift
  Session/Conversations/Message Cells/Content Views/MediaAlbumView.swift
  Session/Conversations/Message Cells/Content Views/MediaView.swift
  Session/Conversations/Message Cells/VisibleMessageCell.swift
Labels: dev-tested, qa-tested

#690 Updated open groups to filter the mentions list based on blinding
  Session/Conversations/ConversationViewModel.swift
Labels: bug

#665 Fix notification sound None not working
  Session.xcodeproj/project.pbxproj
  Session/Meta/AudioFiles/messageReceivedSounds/silence.aiff
  SessionMessagingKit/Utilities/Preferences.swift
Labels: dev-tested

#685 Emoji reacts tweaks
  SessionMessagingKit/Sending & Receiving/Message Handling/MessageReceiver+VisibleMessages.swift
Labels: bug

#687 Voice & video call fix
  Session/Calls/Call Management/SessionCall.swift
  Session/Calls/Call Management/SessionCallManager.swift
  Session/Meta/AppDelegate.swift
  Session/Notifications/AppNotifications.swift
  Session/Notifications/PushRegistrationManager.swift
  SessionMessagingKit/Calls/CurrentCallProtocol.swift
  SessionNotificationServiceExtension/NSENotificationPresenter.swift
  SessionNotificationServiceExtension/NotificationServiceExtension.swift
  SessionShareExtension/ThreadPickerVC.swift
Labels: bug

#691 Disable typing and message requests in open groups if no "write" permission
  Session.xcodeproj/project.pbxproj
  Session/Conversations/ConversationVC+Interaction.swift
  Session/Conversations/ConversationVC.swift
  SessionMessagingKit/Configuration.swift
  SessionMessagingKit/Database/Migrations/_009_OpenGroupPermission.swift
  SessionMessagingKit/Database/Models/OpenGroup.swift
  SessionMessagingKit/Open Groups/OpenGroupManager.swift
  SessionMessagingKit/Shared Models/SessionThreadViewModel.swift
Labels: bug, dev-tested

#693 Fixed a few bugs found during regression testing
  Session.xcodeproj/project.pbxproj
  Session/Conversations/ConversationVC+Interaction.swift
  Session/Conversations/ConversationVC.swift
  Session/Conversations/Message Cells/CallMessageCell.swift
  Session/Meta/AppDelegate.swift
  SessionMessagingKit/Database/Models/Interaction.swift
  SessionMessagingKit/Jobs/Types/DisappearingMessagesJob.swift
  SessionMessagingKit/Messages/Control Messages/ClosedGroupControlMessage.swift
  SessionMessagingKit/Sending & Receiving/Message Handling/MessageReceiver+ClosedGroups.swift
  SessionMessagingKit/Sending & Receiving/Typing Indicators/TypingIndicators.swift
  SessionUtilitiesKit/JobRunner/JobRunner.swift
Labels: bug
