Repository oxen-io/session-ios, pull requests merged in 2023-04, with the labels that each got.

#810 Fix reentrancy crash
  Session/Conversations/ConversationViewModel.swift
  Session/Notifications/AppNotifications.swift
  SessionMessagingKit/Database/Models/SessionThread.swift
  SessionMessagingKit/Messages/Message.swift
  SessionMessagingKit/Shared Models/SessionThreadViewModel.swift
Labels: bug

#811 Updated cocoapods and fixed a XCode 14.3 build error
  Podfile
  Podfile.lock
  SessionMessagingKit/Database/Models/SessionThread.swift
Labels: bug

#812 Updated seed node certificate verification logic
  SessionUtilitiesKit/Networking/HTTP.swift
Labels: bug

#799 Conversation swipe actions
  Podfile.lock
  Session.xcodeproj/project.pbxproj
  Session/Closed Groups/EditClosedGroupVC.swift
  Session/Conversations/Context Menu/ContextMenuVC+Action.swift
  Session/Conversations/ConversationVC+Interaction.swift
  Session/Conversations/Message Cells/InfoMessageCell.swift
  Session/Conversations/Message Cells/MessageCell.swift
  Session/Conversations/Settings/ThreadSettingsViewModel.swift
  Session/Home/HomeVC.swift
  Session/Home/HomeViewModel.swift
  Session/Meta/Translations/de.lproj/Localizable.strings
  Session/Meta/Translations/en.lproj/Localizable.strings
  Session/Meta/Translations/es.lproj/Localizable.strings
  Session/Meta/Translations/fa.lproj/Localizable.strings
  Session/Meta/Translations/fi.lproj/Localizable.strings
  Session/Meta/Translations/fr.lproj/Localizable.strings
  Session/Meta/Translations/hi.lproj/Localizable.strings
  Session/Meta/Translations/hr.lproj/Localizable.strings
  Session/Meta/Translations/id-ID.lproj/Localizable.strings
  Session/Meta/Translations/it.lproj/Localizable.strings
  Session/Meta/Translations/ja.lproj/Localizable.strings
  Session/Meta/Translations/nl.lproj/Localizable.strings
  Session/Meta/Translations/pl.lproj/Localizable.strings
  Session/Meta/Translations/pt_BR.lproj/Localizable.strings
  Session/Meta/Translations/ru.lproj/Localizable.strings
  Session/Meta/Translations/si.lproj/Localizable.strings
  Session/Meta/Translations/sk.lproj/Localizable.strings
  Session/Meta/Translations/sv.lproj/Localizable.strings
  Session/Meta/Translations/th.lproj/Localizable.strings
  Session/Meta/Translations/vi-VN.lproj/Localizable.strings
  Session/Meta/Translations/zh-Hant.lproj/Localizable.strings
  Session/Meta/Translations/zh_CN.lproj/Localizable.strings
  Session/Shared/FullConversationCell.swift
  SessionMessagingKit/Configuration.swift
  SessionMessagingKit/Database/Models/ControlMessageProcessRecord.swift
  SessionMessagingKit/Database/Models/Interaction.swift
  SessionMessagingKit/Jobs/Types/AttachmentDownloadJob.swift
  SessionMessagingKit/Jobs/Types/AttachmentUploadJob.swift
  SessionMessagingKit/Jobs/Types/GroupLeavingJob.swift
  SessionMessagingKit/Jobs/Types/MessageReceiveJob.swift
  SessionMessagingKit/Jobs/Types/MessageSendJob.swift
  SessionMessagingKit/Jobs/Types/NotifyPushServerJob.swift
  SessionMessagingKit/Jobs/Types/SendReadReceiptsJob.swift
  SessionMessagingKit/Sending & Receiving/Message Handling/MessageSender+ClosedGroups.swift
  SessionMessagingKit/Sending & Receiving/MessageSender.swift
  SessionMessagingKit/Shared Models/SessionThreadViewModel.swift
  SessionUIKit/Utilities/UIContextualAction+Theming.swift
  SessionUtilitiesKit/Database/Models/Job.swift
  SessionUtilitiesKit/General/Dictionary+Utilities.swift
  SessionUtilitiesKit/JobRunner/JobRunner.swift
Labels: qa-tested

#814 JobRunner fixes
  Session/Conversations/ConversationVC+Interaction.swift
  Session/Media Viewing & Editing/MediaPageViewController.swift
  SessionMessagingKit/Messages/Control Messages/DataExtractionNotification.swift
  SessionUtilitiesKit/Database/Models/Job.swift
  SessionUtilitiesKit/Database/Models/JobDependencies.swift
  SessionUtilitiesKit/General/Array+Utilities.swift
  SessionUtilitiesKit/JobRunner/JobRunner.swift
Labels: bug

#820 Fixed a couple of issues with seed node requests
  Session.xcodeproj/project.pbxproj
  Session/Meta/Certificates/public-loki-foundation.crt
  Session/Meta/Certificates/public-loki-foundation.der
  Session/Meta/Certificates/seed1-10y.crt
  Session/Meta/Certificates/seed1-10y.der
  Session/Meta/Certificates/seed2-10y.crt
  Session/Meta/Certificates/seed2-10y.der
  Session/Meta/Certificates/seed3-10y.crt
  Session/Meta/Certificates/seed3-10y.der
  Session/Meta/Certificates/storage-seed-1.crt
  Session/Meta/Certificates/storage-seed-1.der
  Session/Meta/Certificates/storage-seed-3.crt
  Session/Meta/Certificates/storage-seed-3.der
  Session/Meta/Session-Info.plist
  SessionSnodeKit/SnodeAPI.swift
  SessionUtilitiesKit/Networking/HTTP.swift
Labels: bug

#792 Swapping video views in call
  Session/Calls/Call Management/SessionCall.swift
  Session/Calls/CallVC.swift
  Session/Calls/Views & Modals/CallVideoView.swift
  SessionMessagingKit/Calls/WebRTCSession+UI.swift
Labels: feature-request, qa-tested

#823 Optimisations and Fixes
  Session/Calls/CallVC.swift
  Session/Conversations/ConversationVC+Interaction.swift
  Session/Conversations/ConversationVC.swift
  Session/Conversations/Settings/OWSMessageTimerView.m
  Session/Utilities/IP2Country.swift
  SessionMessagingKit/Database/Models/Attachment.swift
  SessionMessagingKit/Database/Models/Interaction.swift
  SessionMessagingKit/File Server/FileServerAPI.swift
  SessionMessagingKit/Jobs/Types/GarbageCollectionJob.swift
  SessionMessagingKit/Jobs/Types/MessageSendJob.swift
  SessionMessagingKit/Messages/Visible Messages/VisibleMessage.swift
  SessionMessagingKit/Open Groups/OpenGroupAPI.swift
  SessionMessagingKit/Open Groups/OpenGroupManager.swift
  SessionMessagingKit/Sending & Receiving/MessageReceiver.swift
  SessionMessagingKit/Shared Models/MessageViewModel.swift
  SessionMessagingKit/Shared Models/SessionThreadViewModel.swift
  SessionMessagingKit/Utilities/Preferences.swift
  SessionSnodeKit/SnodeAPI.swift
  SessionUIKit/Utilities/UIView+Utilities.swift
  SessionUtilitiesKit/General/General.swift
  SessionUtilitiesKit/General/UIView+OWS.h
  SessionUtilitiesKit/General/UIView+OWS.m
  SessionUtilitiesKit/JobRunner/JobRunner.swift
  SignalUtilitiesKit/Media Viewing & Editing/Attachment Approval/AttachmentTextToolbar.swift
Labels: bug

#824 Updated the seed node certificates
  Session.xcodeproj/project.pbxproj
  Session/Meta/Certificates/seed1-10y.crt
  Session/Meta/Certificates/seed1-10y.der
  Session/Meta/Certificates/seed1-2023-2y.crt
  Session/Meta/Certificates/seed1-2023-2y.der
  Session/Meta/Certificates/seed2-10y.crt
  Session/Meta/Certificates/seed2-10y.der
  Session/Meta/Certificates/seed2-2023-2y.crt
  Session/Meta/Certificates/seed2-2023-2y.der
  Session/Meta/Certificates/seed3-10y.crt
  Session/Meta/Certificates/seed3-10y.der
  Session/Meta/Certificates/seed3-2023-2y.crt
  Session/Meta/Certificates/seed3-2023-2y.der
  SessionSnodeKit/SnodeAPI.swift
  SessionUtilitiesKit/Networking/HTTP.swift
Labels: bug

#831 Disabled the disappearing messages setting when not a group member
  Session/Conversations/Settings/ThreadDisappearingMessagesViewModel.swift
  Session/Shared/Views/SessionCell+AccessoryView.swift
  SessionMessagingKit/Shared Models/SessionThreadViewModel.swift
  SessionUIKit/Style Guide/Themes/Theme+ClassicDark.swift
  SessionUIKit/Style Guide/Themes/Theme+ClassicLight.swift
  SessionUIKit/Style Guide/Themes/Theme+Colors.swift
  SessionUIKit/Style Guide/Themes/Theme+OceanDark.swift
  SessionUIKit/Style Guide/Themes/Theme+OceanLight.swift
  SessionUIKit/Style Guide/Themes/Theme.swift
Labels: bug

#833 Fix recipientState query bug
  SessionMessagingKit/Shared Models/SessionThreadViewModel.swift
Labels: bug

#834 Removed the iCloud entitlements
  Session/Meta/Signal.entitlements
Labels: feature-request

#835 Fixed a broken share extension
  SessionMessagingKit/Shared Models/SessionThreadViewModel.swift
Labels: bug

#837 Fixed an issue where mentions weren't working
  Session/Conversations/ConversationVC.swift
Labels: bug

#840 Updated permission descriptions to appease Apple
  Session.xcodeproj/project.pbxproj
  Session/Meta/Session-Info.plist
Labels: bug
